import { Html, Head, Main, NextScript } from "next/document";

export default function Document() {
  return (
    <Html>
      <Head>
        <meta
          name="description"
          content="YRHacks - An annual Hackathon run by students, for students! Available to all YRDSB high school students."
        />
        <meta name="theme-color" content="#0E1116" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="apple-touch-icon" href="/logos/logo-96x96.png" />
        <meta name="apple-mobile-web-app-status-bar" content="#0E1116" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://unpkg.com/aos@2.3.1/dist/aos.css"
          rel="stylesheet"
        ></link>
        <link
          rel="preload"
          href="/assets/fonts/HelveticaNeueLTProBdEx.woff"
          as="font"
          crossOrigin=""
          type="font/woff"
        />
        <link
          rel="preload"
          href="\assets\fonts\HelveticaNeueLTProBdEx.woff"
          as="font"
          crossOrigin=""
          type="font/woff"
        />
        <link
          rel="preload"
          href="\assets\fonts\HelveticaNeueLTProBdExO.woff"
          as="font"
          crossOrigin=""
          type="font/woff"
        />
        <link
          rel="preload"
          href="\assets\fonts\HelveticaNeueLTProBlkEx.woff"
          as="font"
          crossOrigin=""
          type="font/woff"
        />
        <link
          rel="preload"
          href="\assets\fonts\HelveticaNeueLTProBlkExO.woff"
          as="font"
          crossOrigin=""
          type="font/woff"
        />
        <link
          rel="preload"
          href="\assets\fonts\HelveticaNeueLTProEx.woff"
          as="font"
          crossOrigin=""
          type="font/woff"
        />
        <link
          rel="preload"
          href="\assets\fonts\HelveticaNeueLTProExO.woff"
          as="font"
          crossOrigin=""
          type="font/woff"
        />
        <link
          rel="preload"
          href="\assets\fonts\HelveticaNeueLTProHvEx.woff"
          as="font"
          crossOrigin=""
          type="font/woff"
        />
        <link
          rel="preload"
          href="\assets\fonts\HelveticaNeueLTProHvExO.woff"
          as="font"
          crossOrigin=""
          type="font/woff"
        />
        <link
          rel="preload"
          href="\assets\fonts\HelveticaNeueLTProLtEx.woff"
          as="font"
          crossOrigin=""
          type="font/woff"
        />
        <link
          rel="preload"
          href="\assets\fonts\HelveticaNeueLTProLtExO.woff"
          as="font"
          crossOrigin=""
          type="font/woff"
        />
        <link
          rel="preload"
          href="\assets\fonts\HelveticaNeueLTProMdEx.woff"
          as="font"
          crossOrigin=""
          type="font/woff"
        />
        <link
          rel="preload"
          href="\assets\fonts\HelveticaNeueLTProMdExO.woff"
          as="font"
          crossOrigin=""
          type="font/woff"
        />
        <link
          rel="preload"
          href="\assets\fonts\HelveticaNeueLTProThEx.woff"
          as="font"
          crossOrigin=""
          type="font/woff"
        />
        <link
          rel="preload"
          href="\assets\fonts\HelveticaNeueLTProThExO.woff"
          as="font"
          crossOrigin=""
          type="font/woff"
        />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
