name: Sync Main to Cloudflare Branch

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Fetch cloudflare branch
      run: |
        git fetch origin cloudflare

    - name: Checkout cloudflare branch
      run: |
        git checkout -b cloudflare origin/cloudflare

    - name: Merge changes from main
      run: |
        git merge main --no-edit

    - name: Push changes to cloudflare branch
      run: |
        git push origin cloudflare
