name: Sync Main to Cloudflare Branch

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push changes to cloudflare branch
      run: |
        git checkout cloudflare
        git merge main --no-edit
        git push origin cloudflare
